Repository dotnet/docs.pt-br, pull requests merged in 2018-10, with the labels that each got.

#76 translation retreat of the repository name
  docs/samples-and-tutorials/index.md
Labels: Accepted, Linguistic Suggestion

#77 translation retreat of the repository name 2
  docs/samples-and-tutorials/index.md
Labels: Accepted, Linguistic Suggestion

#79 table correction
  docs/samples-and-tutorials/index.md
Labels: Accepted, Technical Issue

#85 Fixed typo
  docs/core/docker/docker-basics-dotnet-core.md
Labels: Accepted, Linguistic Suggestion

#86 Fixed some grammar mistakes
  docs/visual-basic/programming-guide/language-features/procedures/auto-implemented-properties.md
  docs/visual-basic/programming-guide/language-features/procedures/how-to-protect-a-procedure-argument-against-value-changes.md
Labels: In Progress, Linguistic Suggestion
