Repository dotnet/docs.pt-br, pull requests merged in 2019-02, with the labels that each got.

#109 Fix Portuguese Terminology
  docs/standard/containerized-lifecycle-architecture/docker-terminology.md
Labels: Accepted With Changes, Linguistic Suggestion

#110 fixed phrase in portuguese
  docs/standard/containerized-lifecycle-architecture/docker-containers-images-and-registries.md
Labels: Accepted, Linguistic Suggestion

#112 Increase the translation for PT-BR
  docs/standard/datetime/choosing-between-datetime.md
Labels: Linguistic Suggestion, Partially Accepted
